### ISSUE TITLE
UnlockingPanel

### ISSUE THREAD

**Issue by originalfoo** [keallu/CSL-HideIt#1]
Always pops up when I start a new map with the 'unlock all' mod enabled; bit tiresome when testing mods.

Could an option be added to hide it?

**Comment by keallu** [comment]
If you are testing mods, why don't you just load a saved game? I have specific saved games which are made for testing...

**Comment by originalfoo** [comment]
When testing TMPE we check on both saved games and new games. New games are often used when trying to track down pathfinding bugs as we can minimise any issues that might arise from existing roads and potentially broken data in user-submitted savegames.

**Comment by keallu** [comment]
This was added in 1.12.
