### ISSUE TITLE
Add tooltips to explain options

### ISSUE THREAD

**Issue by iTob191** [keallu/CSL-HideIt#11]
I have some trouble finding out what some of the config options really do. For example, what's the difference between "Grass Pollution Ground Color" and "Pollution Area"? What is "Volume fog" (just figured out that these are the "clouds" in game)? What is "Steam" in the game? ...
I'd suggest adding tooltips to all options that explain their functionality.

**Comment by keallu** [comment]
That will be a huge job to explain everything. Not in scope for the moment.
