### ISSUE TITLE
Hiding "Chirper button" does not prevent sound

### ISSUE THREAD

**Issue by iTob191** [keallu/CSL-HideIt#12]
The new message sound of the chirper does still play, even with the chirper button disabled.

This isn't really a bug because the options panel does not mention the sound. Anyway, I think most players expect this feature to disable Chirper completely. In addition, in the [steam discussion](https://steamcommunity.com/workshop/filedetails/discussion/1591417160/3561682880012019131/) it is stated that *Hide it!* does replace *Chirpy Exterminator* and the latter does prevent the sound from playing AFAIK.

**Comment by keallu** [comment]
That makes sense. I've added it to my todo list and will possible be included in a future release.
