### ISSUE TITLE
Conflict with Theme Mixer 2

### ISSUE THREAD

**Issue by originalfoo** [keallu/CSL-HideIt#14]
When using Theme Mixer 2, there seems to be some conflict with the "hide sprites" stuff (grass, fertile, cliff). The most common side effect is that all the grass/fertile sprites are always hidden, even if both TM2 and Hide It set them as enabled.

Could you update Hide It to not apply it's sprite decorations settings when TM2 is active?

**Comment by keallu** [comment]
If you are using TM2 as such, you just avoid hiding grass/fertile sprites with Hide It!

I've added it to my todo list but it is low priority.
