### ISSUE TITLE
Conflict with `No Radioactive Desert And More!`

### ISSUE THREAD

**Issue by originalfoo** [keallu/CSL-HideIt#15]
When NRDAM mod is active, it clashes with Hide It causing all resource textures to disappear from map (user can't see where resources are in the info views).

https://steamcommunity.com/sharedfiles/filedetails/?id=666425898&searchtext=No+Radioactive+Desert+And+More

**Comment by keallu** [comment]
Why use both Hide It! and NRDAM? Hide It! is very much a replacement for NRDAM.

**Comment by originalfoo** [comment]
Yup, that kind of conflict would be better reported to user via the Compatibility Report mod - see linked issue above.

**Comment by keallu** [comment]
Agreed :) Enjoy your weekend, @aubergine10 :)
