### ISSUE TITLE
Hide ruining on networks and buildings

### ISSUE THREAD

**Issue by chameleon-tbn** [keallu/CSL-HideIt#17]
Building and Networks also create a ruining as Prop and Trees do. For detailers this is very annoying. Therefore a Hide It Option for that would be great.

![image](https://user-images.githubusercontent.com/37211016/97018959-088da680-1550-11eb-9cd8-876cff92be8c.png)

**Comment by keallu** [comment]
I've looked into this before but it is not as easy to implement. I will add it though to my todo list and maybe have it included in a future update.
