### ISSUE TITLE
"Hello" TutorialAdvisorPanel

### ISSUE THREAD

**Issue by originalfoo** [keallu/CSL-HideIt#2]
Despite having tutorial turned off in game settings, the "Hello!" panel always pops up when starting a new game.

Could an option be added to hide it?

**Comment by keallu** [comment]
I think if you hide the Advisor button with Hide It!, then you are not prompted with this?

**Comment by originalfoo** [comment]
Hi, sorry for taking ages to reply. I just checked now and hiding advisor button doesn't hide the "hello" initial help panel (even when vanilla "show in-game guide popups" option disabled).

![advisor](https://user-images.githubusercontent.com/1386719/53523089-c5a5d200-3ad3-11e9-92af-bd72fb30cdf2.gif)

**Comment by keallu** [comment]
This was added in 1.13.
