### ISSUE TITLE
[Hide It!] BuildingPropsHelper:UpdateProps -> Exception: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by originalfoo** [keallu/CSL-HideIt#3]
```
[Hide It!] BuildingPropsHelper:UpdateProps -> Exception: Object reference not set to an instance of an object
```

and also

```
[Hide It!] NetPropsHelper:UpdateLaneProps -> Exception: Object reference not set to an instance of an object
```

Seeing lots (probably thousands) of these errors in the log

I've turned off **Hedges** and **Buoys** in the props section.

Suggestion: Add details about what prop it's trying to hide in error message?

**Comment by keallu** [comment]
Hide It! looks for props in in building prefabs and removes them by name. Specific for hedges { "hedge", "hedge2", "Hedge 01", "Hedge 02" }.

If you have a lot of assets with similar names, they should be removed, but if some assets are configured a bit unordinary that might provoke errors. With Vanilla game and Hide It!, I have not been able to provoke this error.

Can you test like that and see what happens just to narrow down the problem)?

**Comment by originalfoo** [comment]
Was going to build locally to investigate what's causing it but blocked by #5

**Comment by keallu** [comment]
Reopen if you find out anything new.
