### ISSUE TITLE
Disable edge fog not working

### ISSUE THREAD

**Issue by originalfoo** [keallu/CSL-HideIt#4]
I'm not sure if it's happening consistently (will do more testing this evening and report back) but I've just noticed that the edge fog wasn't turning off despite it being disabled in the mod options.

Source code link: https://github.com/keallu/CSL-HideIt/blob/master/HideIt/HiderTool.cs#L653

All the others were turning off as far as I could tell (volume, pollution, distance) so it seems limited to the edge fog. I tried enable/disable the option in-game, allowing some frames to pass between each toggling, but didn't see any change.

BTW, I was looking at Cloud & Fog Toggler mod source code and noticed there are some additional items in there that its affecting - probably not relevant to edge fog, but might impact on some of the other clouds/fog:

https://github.com/bloodypenguin/Skylines-FogOptions/blob/master/FogOptions/FogController.cs

**Comment by keallu** [comment]
Yes, I know that Cloud & Fog Toggler has additional code. When I tested it wasn't necessary for what I saw but I think it is one of the problems in regards to Daylight Classic.

**Comment by originalfoo** [comment]
I'll do some testing with and without daylight classic mod to see what happens.

**Comment by originalfoo** [comment]
I've unsubbed daylight classic and the problem persists. Also unsubbed all the various eye candy mods.

Maybe it's a map biome thing?

**Comment by originalfoo** [comment]
I'm no longer able to reproduce this issue so closing ticket.
