### ISSUE TITLE
Feature to allow change of pollution colour?

### ISSUE THREAD

**Issue by originalfoo** [keallu/CSL-HideIt#7]
While not technically hiding something, would this mod be viable place to choose different colours for polluted land and water?

Would replace a load of different mods, many of which are listed in description here: https://steamcommunity.com/sharedfiles/filedetails/?id=407795371

**Comment by originalfoo** [comment]
Here's list of pollution (water and ground) color changing mods I've found so far - many are buggy:

```
            407270433,  // * No more purple pollution (normal grass) .
            407795371,  // * No more purple pollution (brown grass) .
            407810495,  // * No more purple pollution (tan grass) .
            407842191,  // * No more purple pollution (red-brown grass) .
            407890452,  // * No more purple pollution (grey grass) .
            482360157,  // * No more purple pollution (radioactive green grass) .
            408126080,  // * No more purple pollution (brown water) .
            408126282,  // * No more purple pollution (green water) .
            408190203,  // * No more purple pollution (muddy water) .
            408189919,  // * No more purple pollution (silty water) .
            408167727,  // * No more purple pollution (radioactive green water) .
            491002883,  // Pale Green Pollution (Tropical Boreal) .
            490998828,  // Pale Green Pollition (Temperate) .
            491003892,  // Pale Green Pollution (European) .
```

**Comment by originalfoo** [comment]
Actually, it might be worth doing a "Color It!" mod - could also include:

* Selector colors
* Zone colors
* Land colors (eg. replace [environment color changer](https://steamcommunity.com/sharedfiles/filedetails/?id=554680908) mod, and a bunch of others)

**Comment by keallu** [comment]
Yes, I think this is for a different mod, Maybe "Color It!", yes :-)
