### ISSUE TITLE
Key shortcut to toggle hiding of buildings

### ISSUE THREAD

**Issue by originalfoo** [keallu/CSL-HideIt#8]
Similar to what this now-defunct mod did: https://steamcommunity.com/sharedfiles/filedetails/?id=417926819

![steamuserimages-a akamaihd](https://user-images.githubusercontent.com/1386719/53675128-612d7300-3c8b-11e9-8578-e6255853ebef.jpg)

**Comment by keallu** [comment]
I might add it to Toggle It!
